nelmio_api_doc:
    documentation:
        info:
            title: "Mon API"
            description: "Documentation de l'API"
            version: "1.0.0"
        servers:
            - url: 'http://localhost/api'  # URL de l'API
    areas:
        default:
            path_patterns:
                - '^/api'  # Applique la documentation aux routes commençant par /api

